project:
  type: website
  output-dir: ../docs

execute:
  # freeze: auto
  echo: false
  warning: false
  
website:
  title: "Website-Title"
  # google-analytics: "UA-121215066-1"
  reader-mode: false
  page-footer: Beep Boop Stats
  # top nav
  navbar:
    pinned: true
    logo: ../assets/img/favicon.png
    search: true
    left:
      # - text: "Home"
      #   file: index.qmd
      - text: "Book Appointments"
        file: book_appointments.qmd
      - text: "Instagram"
        file: instagram.qmd
      - text: "Contact"
        file: contact/index.qmd

format:
  html:
    theme: 
      light: 
        - pulse
        - assets/css/styles.scss
      dark: 
        - darkly
        - assets/css/styles.scss
    fontsize: 1.1em
    page-layout: full
    toc: true
    toc-depth: 4
    toc-location: left
    toc-expand: 1
    embed-resources: true
    # new options
    toc_float: true
    code-overflow: wrap
    code-fold: true
    code-summary: "Show code"

format-links: []
