project:
  type: website
  output-dir: ../docs

execute:
  # freeze: auto
  echo: false
  warning: false
  
website:
  title: "Website Title Here"
  google-analytics: "UA-121215066-1"
  reader-mode: false
  page-footer: Beep Boop Stats
  # top nav
  navbar:
    pinned: true
    logo: ../assets/img/favicon.png
    search: true
    left:
      # - text: "Home"
      #   file: index.qmd
      - text: "Contact"
        file: contact/index.qmd

format:
  html:
    fontsize: 1.3em
    theme: solar
    page-layout: full
    toc: true
    toc-depth: 4
    toc-location: left
    toc-expand: 1
    embed-resources: true
    # new options
    toc_float: true
    code-overflow: wrap
    code-fold: true
    code-summary: "Show code"

format-links: []
